hw13_2git/hw13_2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hw13_2git/quotes/urls.py
# from django.shortcuts import render
from django.urls import path
from . import views

app_name = "quotes"

urlpatterns = [
    path("", views.main_view, name="main"),
    path("<int:page>", views.main_view, name="main_paginate"),
    path("<str:tag_name>", views.main_view_tag, name="main_tag"),
    path('t10tag/', views.t10tag, name='t10tag'),
    path('tag/', views.tag_change, name='tag'),
    path('quote/', views.quote_change, name='quote'),
    path('author/', views.author_change, name='author'),
    path('authorshow/<int:author_id>', views.author_show, name='author_show'),
]

hw13_2git/users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from . import views


app_name = 'users'


urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html', success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

hw13_2git/quotes/models.py
from django.db import models


class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.fullname}"


class Tag(models.Model):
    name = models.CharField(max_length=30, null=False, unique=True )

    def __str__(self):
        return f"{self.name}"


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.quote[:50]} ..."

hw13_2git/quotes/forms.py
from django.forms import ModelForm, CharField, TextInput, DateTimeField, Textarea
from . models import Author, Tag, Quote


class TagForm(ModelForm):
    name = CharField(min_length=3, max_length=30, required=True, widget=TextInput())
    
    class Meta:
        model = Tag
        fields = ['name']


class AuthorForm(ModelForm):
    fullname = CharField(min_length=3, max_length=50, required=True, widget=TextInput())
    born_date = CharField(max_length=50, widget=TextInput())
    born_location = CharField(max_length=150, widget=TextInput())
    description = CharField(widget=Textarea())
    created_at = DateTimeField(required=False)

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']


class QuoteForm(ModelForm):
    quote = CharField(min_length=5, required=True, widget=Textarea())
    author = CharField(min_length=5, required=True, widget=TextInput())
    created_at = DateTimeField(required=False)

    class Meta:
        model = Quote
        fields = ['author', 'quote']
        exclude = ['tags']

hw13_2git/quotes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from . models import Author, Tag, Quote
from . forms import TagForm , QuoteForm, AuthorForm
# from operator import itemgetter


toptags = [{'t':'_', 'n':'?', 's':'28'}, {'t':'_', 'n':'?', 's':'26'}, {'t':'_', 'n':'?', 's':'24'}, 
           {'t':'_', 'n':'?', 's':'22'}, {'t':'_', 'n':'?', 's':'20'}, {'t':'_', 'n':'?', 's':'18'}, 
           {'t':'_', 'n':'?', 's':'16'}, {'t':'_', 'n':'?', 's':'14'}, {'t':'_', 'n':'?', 's':'12'}, {'t':'_', 'n':'?', 's':'12'}]
cur_page = 1


def get_tagquotes(quotes, tag_name):
    tagquotes = []
    for quote in quotes:            
        for name in quote.tags.all():     
            if tag_name == str(name):
                tagquotes.append(quote)
                break
    return tagquotes


def main_view(request, page=0):
    global cur_page
    quotes = Quote.objects.all()
    if page > 0:
        cur_page = page
    paginator = Paginator(list(quotes), 10, orphans=2) # Show 10 quotes per page.
    page_quotes = paginator.page(cur_page)
    return render(request, "quotes/main.html", context={'quotes': page_quotes, 'toptags': toptags, 'curtag': ''})


def main_view_tag(request, tag_name=''):
    quotes = Quote.objects.all()    # ?? quotes_tags = Quote.objects.values_list('tags')
    if tag_name == '':
        tagquotes = quotes
        tag_head = ''    
    else:    
        get_tag = get_tagquotes(quotes, tag_name)
        tagquotes = quotes if len(get_tag) == 0  else get_tag
        tag_head = f"'{tag_name}' ({len(get_tag)}):"
    return render(request, "quotes/main.html", context={'quotes': tagquotes, 'toptags': toptags, 'curtag': tag_head})


def t10tag(request):
    tags_dict = {}  # {'tag': int, 'tag': int, 'tag': int, ... key: value} 
    quotes = Quote.objects.all()    # ?? quotes_tags = Quote.objects.values_list('tags')
    for quote in quotes:
        for name in quote.tags.all():      
            key = str(name)
            tags_dict[key] = tags_dict[key] + 1  if key in tags_dict.keys() else 1
    # tags_dict = dict(sorted(tags_dict.items(), key=itemgetter(1), reverse=True))  # use itemgetter()
    tags_dict = dict(sorted(tags_dict.items(), key=lambda item: item[1], reverse=True))
    i = 0
    for key, val in tags_dict.items():
        toptags[i]['t'] = f"{key}"
        toptags[i]['n'] = f"{key} ({val})"
        i += 1
        if i > 9:
            break
    return redirect(to='quotes:main')


def author_show(request, author_id):
    author = get_object_or_404(Author, pk=author_id)        
    return render(request, 'quotes/authorshow.html', {"author": author})


@login_required
def tag_change(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:main')
        else:
            return render(request, 'quotes/tag.html', {'form': form})
    return render(request, 'quotes/tag.html', {'form': TagForm()})


@login_required
def author_change(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:main')
        else:
            # print("author form is NOT valid !!!   ", form.errors)
            return render(request, 'quotes/author.html', {'form': form})
    return render(request, 'quotes/author.html', {'form': AuthorForm()})


@login_required
def quote_change(request):
    tags = Tag.objects.all().order_by("name")    #.filter(user=request.user)
    auths = Author.objects.all().order_by("fullname")

    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save()
            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)
            return redirect(to='quotes:main')
        else:
            return render(request, 'quotes/quote.html', {"tags": tags, "auths": auths, 'form': form})
    return render(request, 'quotes/quote.html', {"tags": tags, "auths": auths, 'form': QuoteForm()})
    


hw13_2git/quotes/templates/quotes/author.html
{% extends "quotes/base.html" %}
{% block content %}

<form method="POST" action="{% url 'quotes:author' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the author fullname:
            {{ form.fullname }}
        </label>
        <span>{{ form.errors.fullname }}</span>
    </div>
    
    <div style="padding: 10px">
        <label>Enter the date of birth:
            {{ form.born_date }}
        </label>
        <span>{{ form.errors.born_date }}</span>
    </div>

    <div style="padding: 10px">
        <label>Enter the birth location:
            {{ form.born_location }}
        </label>
        <span>{{ form.errors.born_location }}</span>
    </div>

    <div style="padding: 10px">
        <label>Enter the description:
            {{ form.description }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

hw13_2git/quotes/templates/quotes/authorshow.html
{% extends "quotes/base.html" %} 
{% block content %}

<h1>{{author.fullname}}</h1>

<p>Date of birth: <b>{{author.born_date}}</b></p>
<p>Birth location: <b>{{author.born_location}}</b></p>
<p>Description: <b>{{author.description}}</b></p>
<p>Time of creation: <kbd>{{author.created_at}}</kbd></p>

{% endblock %}

hw13_2git/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Note information</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
</head>
<body>
<main class="container">
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        <ul>
            <li><a href="/" role="button"> Go back to the main page </a></li>
        </ul>
    </nav>
    {% block content %} {% endblock %}
</main>
</body>
</html>

hw13_2git/quotes/templates/quotes/main.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Home Work Quotes</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'quotes/main.css' %}">
</head>

<body>
    <div class="container">

        {% load extract %}
        <div class="row">
            <div class="col-md-8">
                <div class="row header-box">
                    <h1><a href="/" style="text-decoration: none">Home Work: Quotes</a></h1>
                </div>

                {% if curtag != '' %}
                    <h4 style="text-align: left">Quotes for tag <b>{{ curtag }}</b></h4>
                {% endif %}

                {% for quote in quotes %}
                    <div class="quote">
                        <span class="text" itemprop="text">{{quote.quote}}</span>
                        <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
                            <a href="{% url 'quotes:author_show' quote.author.id %}" role="button">(about)</a>
                        </span>
                        <div class="tags">
                            Tags:
                            {% for tag in quote.tags|get_tags %}
                            {# <a class="tag" href="/{{tag}}">{{tag}}</a> #}
                            <a class="tag" href="{% url 'quotes:main_tag' tag %}">{{tag}}</a>
                            {% endfor %}
                        </div>
                    </div>
                {% empty %}
                    <li>No quotes</li>
                {% endfor %}

                <nav>
                    <ul class="pager">
                        {% if curtag == '' %}
                        {% if quotes.has_previous %}
                        <li class="previous">
                            <a href="{% url 'quotes:main_paginate' 1 %}">First</a>
                        </li>
                        <li class="previous">
                            <a href="{% url 'quotes:main_paginate' quotes.previous_page_number %}"><span
                                    aria-hidden="true">&laquo;</span> Previous</a>
                        </li>
                        {% endif %}

                        <li class="tags">
                            Page {{ quotes.number }} of {{ quotes.paginator.num_pages }}.
                        </li>

                        {% if quotes.has_next %}
                        <li class="next">
                            <a href="{% url 'quotes:main_paginate' quotes.paginator.num_pages %}">Last</a>
                        </li>
                        <li class="next">
                            <a href="{% url 'quotes:main_paginate' quotes.next_page_number %}">Next<span
                                    aria-hidden="true"> &raquo;</span></a>
                        </li>
                        {% endif %}
                        {% endif %}
                    </ul>
                </nav>
            </div>

            <div class="col-md-4 tags-box">
                <div class="row header-box">
                    <p style="height: 30px"> </p>
                </div>

                <h2 style="text-align: center">Top Ten tags</h2>
                {% if toptags.0.t != '_' %}
                    {% for toptag in toptags %}
                    <span class="tag-item" style="text-align: center">
                        <a class="tag" style="font-size: {{toptag.s}}px" href="{% url 'quotes:main_tag' toptag.t %}">{{toptag.n}}</a>
                    </span>
                    {% endfor %}
                    <hr style="height: 2px; width: 50%">
                {% endif %}

                <!-- <span class="tag-item" style="text-align: center">
                    <a class="tag tt1"  
                    href="{% url 'quotes:main_tag' toptags.0.t %}">{{toptags.0.n}}</a>
                </span>
                <span class="tag-item" style="text-align: center">
                    <a class="tag tt2" 
                        href="{% url 'quotes:main_tag' toptags.1.t %}">{{toptags.1.n}}</a>
                </span>
                <span class="tag-item" style="text-align: center">
                    <a class="tag tt3" 
                        href="{% url 'quotes:main_tag' toptags.2.t %}">{{toptags.2.n}}</a>
                </span> -->

                <span class="tag-item" style="text-align: center">
                    <a class="tag" style="font-size: 22px" href="{% url 'quotes:t10tag' %}">Update Top Ten tags</a>
                </span>
                <hr style="height: 4px; width: 80%">

                {% if user.is_authenticated %}
                <h3 style="text-align: center">Welcome <b>{{ user.username }}!</b></h3>

                <span class="tag-item" style="text-align: center">
                    <a class="tag" style="font-size: 22px" href="{% url 'users:logout' %}" role="button">Logout</a>
                </span>
                <hr style="height: 2px;">
                <span class="tag-item" style="text-align: center">
                    <a class="tag" style="font-size: 22px" href="{% url 'quotes:author' %}" role="button">Add author</a>
                </span>
                <span class="tag-item" style="text-align: center">
                    <a class="tag" style="font-size: 22px" href="{% url 'quotes:tag' %}" role="button">Add tag</a>
                </span>
                <span class="tag-item" style="text-align: center">
                    <a class="tag" style="font-size: 22px" href="{% url 'quotes:quote' %}" role="button">Add quotes</a>
                </span>

                {% else %}
                <h3 style="text-align: center">Sign Up or Login:</h3>
                <span class="tag-item" style="text-align: center">
                    <a class="tag" style="font-size: 22px" href="{% url 'users:signup' %}" role="button">Sign Up</a>
                </span>
                <span class="tag-item" style="text-align: center">
                    <a class="tag" style="font-size: 22px" href="{% url 'users:login' %}" role="button">Login</a>
                </span>
                {% endif %}
                
            </div>
        </div>
    </div>

    <footer class="footer">
        <div class="container">
            <p class="text-muted">
                Quotes by: <a href="https://www.goodreads.com/quotes">GoodReads.com</a>
            </p>
        </div>
    </footer>
</body>

</html>

hw13_2git/quotes/templates/quotes/quote.html
{% extends "quotes/base.html" %}
{% block content %}

<form method="POST" action="{% url 'quotes:quote' %}">
    {% csrf_token %}
    
    <div style="padding: 10px">
        <label> Select authors:
            <select name="author" required>
                {% for auth in auths %}
                <option value="{{auth.fullname}}">{{auth.fullname}}</option>
                {% endfor %}
            </select>
        </label>
    </div>      
    
    <div style="padding: 10px">
        <label> Quote text:
            {{ form.quote }}
        </label>
        <span>{{ form.errors.quote }}</span>
    </div>

    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>    

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

hw13_2git/quotes/templates/quotes/tag.html
{% extends "quotes/base.html" %}
{% block content %}

<form method="POST" action="{% url 'quotes:tag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{ form.name }}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}